=begin comment

SMS Fusion API

This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::SMSApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# send_sms
#
# Send an SMS
# 
# @param string $key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt; (required)
# @param ARRAY[string] $num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s (required)
# @param string $msg Message content to send (required)
# @param string $from MSISDN or vanity alphanumeric source number (optional)
# @param string $deliverby UTC encoded time to send the SMS (optional)
# @param string $dlrcb HTTP or HTTPS callback URL for delivery reports. Timeout for callbacks is set to 30 seconds (optional)
# @param string $replycb HTTP or HTTPS callback URL for replies. Timeout for callbacks is set to 30 seconds (optional)
# @param string $replyemail Email address to send replies to (optional)
# @param int $validity Time in minutes to keep the SMS valid for (optional)
# @param string $cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally (optional)
{
    my $params = {
    'key' => {
        data_type => 'string',
        description => 'API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;',
        required => '1',
    },
    'num' => {
        data_type => 'ARRAY[string]',
        description => 'Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s',
        required => '1',
    },
    'msg' => {
        data_type => 'string',
        description => 'Message content to send',
        required => '1',
    },
    'from' => {
        data_type => 'string',
        description => 'MSISDN or vanity alphanumeric source number',
        required => '0',
    },
    'deliverby' => {
        data_type => 'string',
        description => 'UTC encoded time to send the SMS',
        required => '0',
    },
    'dlrcb' => {
        data_type => 'string',
        description => 'HTTP or HTTPS callback URL for delivery reports. Timeout for callbacks is set to 30 seconds',
        required => '0',
    },
    'replycb' => {
        data_type => 'string',
        description => 'HTTP or HTTPS callback URL for replies. Timeout for callbacks is set to 30 seconds',
        required => '0',
    },
    'replyemail' => {
        data_type => 'string',
        description => 'Email address to send replies to',
        required => '0',
    },
    'validity' => {
        data_type => 'int',
        description => 'Time in minutes to keep the SMS valid for',
        required => '0',
    },
    'cc' => {
        data_type => 'string',
        description => '2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'send_sms' } = { 
    	summary => 'Send an SMS',
        params => $params,
        returns => 'SMSResult',
        };
}
# @return SMSResult
#
sub send_sms {
    my ($self, %args) = @_;

    # verify the required parameter 'key' is set
    unless (exists $args{'key'}) {
      croak("Missing the required parameter 'key' when calling send_sms");
    }

    # verify the required parameter 'num' is set
    unless (exists $args{'num'}) {
      croak("Missing the required parameter 'num' when calling send_sms");
    }

    # verify the required parameter 'msg' is set
    unless (exists $args{'msg'}) {
      croak("Missing the required parameter 'msg' when calling send_sms");
    }

    # parse inputs
    my $_resource_path = '/sms/';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'key'}) {
        $query_params->{'key'} = $self->{api_client}->to_query_value($args{'key'});
    }

    # query params
    if ( exists $args{'num'}) {
        $query_params->{'num'} = $self->{api_client}->to_query_value($args{'num'});
    }

    # query params
    if ( exists $args{'msg'}) {
        $query_params->{'msg'} = $self->{api_client}->to_query_value($args{'msg'});
    }

    # query params
    if ( exists $args{'from'}) {
        $query_params->{'from'} = $self->{api_client}->to_query_value($args{'from'});
    }

    # query params
    if ( exists $args{'deliverby'}) {
        $query_params->{'deliverby'} = $self->{api_client}->to_query_value($args{'deliverby'});
    }

    # query params
    if ( exists $args{'dlrcb'}) {
        $query_params->{'dlrcb'} = $self->{api_client}->to_query_value($args{'dlrcb'});
    }

    # query params
    if ( exists $args{'replycb'}) {
        $query_params->{'replycb'} = $self->{api_client}->to_query_value($args{'replycb'});
    }

    # query params
    if ( exists $args{'replyemail'}) {
        $query_params->{'replyemail'} = $self->{api_client}->to_query_value($args{'replyemail'});
    }

    # query params
    if ( exists $args{'validity'}) {
        $query_params->{'validity'} = $self->{api_client}->to_query_value($args{'validity'});
    }

    # query params
    if ( exists $args{'cc'}) {
        $query_params->{'cc'} = $self->{api_client}->to_query_value($args{'cc'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('SMSResult', $response);
    return $_response_object;
}

1;
