=begin comment

SMS Fusion API

This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::DefaultApi');

my $api = WWW::SwaggerClient::DefaultApi->new();
isa_ok($api, 'WWW::SwaggerClient::DefaultApi');

#
# get_hlr test
#
{
    my $key = undef; # replace NULL with a proper value
    my $num = undef; # replace NULL with a proper value
    my $cc = undef; # replace NULL with a proper value
    my $result = $api->get_hlr(key => $key, num => $num, cc => $cc);
}

#
# get_hlr_callback test
#
{
    my $key = undef; # replace NULL with a proper value
    my $num = undef; # replace NULL with a proper value
    my $cb = undef; # replace NULL with a proper value
    my $cc = undef; # replace NULL with a proper value
    my $result = $api->get_hlr_callback(key => $key, num => $num, cb => $cb, cc => $cc);
}


1;
