=begin comment

SMS Fusion API

This is the SMS Fusion API

OpenAPI spec version: 1.0.0
Contact: support@smsfusion.com.au
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::SMSApi');

my $api = WWW::SwaggerClient::SMSApi->new();
isa_ok($api, 'WWW::SwaggerClient::SMSApi');

#
# send_sms test
#
{
    my $key = undef; # replace NULL with a proper value
    my $num = undef; # replace NULL with a proper value
    my $msg = undef; # replace NULL with a proper value
    my $from = undef; # replace NULL with a proper value
    my $deliverby = undef; # replace NULL with a proper value
    my $dlrcb = undef; # replace NULL with a proper value
    my $replycb = undef; # replace NULL with a proper value
    my $replyemail = undef; # replace NULL with a proper value
    my $validity = undef; # replace NULL with a proper value
    my $cc = undef; # replace NULL with a proper value
    my $result = $api->send_sms(key => $key, num => $num, msg => $msg, from => $from, deliverby => $deliverby, dlrcb => $dlrcb, replycb => $replycb, replyemail => $replyemail, validity => $validity, cc => $cc);
}


1;
